import { shoppingItem } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import ItemModal from "../components/ItemModal";
import { itemsRouter } from "../server/trpc/router/example";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [items, setItems] = useState<shoppingItem[]>([]);
  const [modalOpen, setModalOpen] = useState<boolean>(false);
  const {} = trpc.items.addItem.useMutation();

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {modalOpen && <ItemModal />}
      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My shopping list</h2>
          <button
            onClick={() => setModalOpen(true)}
            type="button"
            className="trasition rounded-md bg-orange-500 p-2 text-sm text-white hover:bg-orange-600"
          >
            Add shoping item
          </button>
        </div>
        <ul className="mt-4">
          {["orange", "mango"].map((item) => (
            <li key={item.id} className="flex items-center justify-between">
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
